export const StringLink = {
  dashboard: "/",
  news: "/news",
  tambahMitra: "/register",
  stockis: "/stockis",
  orderStockis: "/stockis/order",
  pembelian: "/pembelian",
  checkout: "/pembelian/checkout",
  invoiceMitra: "/mitra/invoice",
  address: "/address",
  profile: "/profile",
  genealogy: "/genealogy",
  genealogyPraPosting: "/genealogy/pra-posting",
  genealogyMonolegNasional: "/genealogy/monoleg-nasional",
  product: "/product",
  invoiceProduct: "/invoice",
  // checkout: "/product/checkout",
  withdraw: "/wallet/withdraw",
  deposit: "/wallet/deposit",
  reportWithdraw: "/withdraw/report",
  reportTransaction: "/report/transaction",
  reportPurchase: "/report/purchase",
  transactionRecycle: "/recycle",
  invoiceRecycle: "/recycle/invoice",
  news: "/news",
  detailNews: "/news/:id_berita",
};
