export const STRING_COOKIES = {
  token: "__kolabiz__token",
  user: "__kolabiz__user",
  info: "__kolabiz__info",
  address: "__kolabiz__address",
  bank: "__kolabiz__bank",
};

export const LOGIN = {
  SUCCESS: "LOGIN_SUCCESS",
  LOADING: "LOGIN_LOADING",
};

export const AUTH_USER = {
  DATA_USER_LOGIN: "DATA_USER_LOGIN",
  DATA_INFO: "DATA_INFO",
  DATA_USER_DETAIL: "DATA_USER_DETAIL",
  DATA_PIN: "DATA_PIN",
  LOADING: "LOADING_LOGIN",
  LOADING_PIN: "LOADING_PIN",
  VALIDATE_USERNAME: "VALIDATE_USERNAME",
  LOADING_VALIDATE_USERNAME: "LOADING_VALIDATE_USERNAME",
  DATA_SIGNUP: "DATA_SIGNUP",
  LOADING_SIGNUP: "LOADING_SIGNUP",
  DATA_RESEND_EMAIL: "DATA_RESEND_EMAIL",
  LOADING_RESEND_EMAIL: "LOADING_RESEND_EMAIL",
};

export const ADDRESS = {
  DATA_PROVINCE: "DATA_PROVINCE",
  LOADING_PROVINCE: "LOADING_PROVINCE",
  DATA_CITY: "DATA_CITY",
  LOADING_CITY: "LOADING_CITY",
  DATA_DISTRICTS: "DATA_DISTRICTS",
  LOADING_DISTRICTS: "LOADING_DISTRICTS",
};

export const BANKS = {
  DATA_BANK_MEMBER: "DATA_BANK_MEMBER",
  LOADING_BANK_MEMBER: "LOADING_BANK_MEMBER",
  DATA_BANK_COMPANY: "DATA_BANK_COMPANY",
  LOADING_DATA_BANK_COMPANY: "LOADING_DATA_BANK_COMPANY",
  DATA_BANK_GENERAL: "DATA_BANK_GENERAL",
  LOADING_DATA_BANK_GENERAL: "LOADING_DATA_BANK_GENERAL",
};

export const STOCKIS = {
  SUCCESS: "STOCKIS_SUCCESS",
  LOADING: "STOCKIS_LOADING",
  DATA: "STOCKIS_DATA",
  DETAIL: "STOCKIS_DATA_DETAIL",
  LOADING_DETAIL: "STOCKIS_LOADING_DETAIL",
  LOADING_DATA: "STOCKIS_LOADING_DATA",
  ORDER: "STOCKIS_ORDER_DATA",
  LOADING_ORDER: "STOCKIS_ORDER_LOADING",
  APPROVE_ORDER: "STOCKIS_APPROVE_ORDER",
  LOADING_APPROVE_ORDER: "STOCKIS_LOADING_APPROVE_ORDER",
  CANCEL_ORDER: "STOCKIS_CANCEL_ORDER",
  LOADING_CANCEL_ORDER: "STOCKIS_LOADING_CANCEL_ORDER",
  TAKE_ORDER: "STOCKIS_TAKE_ORDER",
  LOADING_TAKE_ORDER: "STOCKIS_LOADING_TAKE_ORDER",
};

export const MEMBER = {
  LOADING: "MEMBER_LOADING",
  LOADING_GENEALOGY: "LOADING_GENEALOGY",
  DATA_GENEALOGY: "DATA_GENEALOGY",
};

export const INFO = {
  LOADING: "INFO_LOADING",
  DATA: "INFO_DATA",
};

export const PAYMENT_CHANNEL = {
  LOADING: "PAYMENT_CHANNEL_LOADING",
  DATA: "PAYMENT_CHANNEL_DATA",
};

export const PAKET = {
  LOADING_REGISTER: "LOADING_REGISTER",
  DATA_REGISTER: "DATA_REGISTER",
  LOADING_SMART_CONTRACT: "LOADING_SMART_CONTRACT",
  DATA_SMART_CONTRACT: "DATA_SMART_CONTRACT",
  LOADING_HAPPY_SHOPPING: "LOADING_HAPPY_SHOPPING",
  DATA_HAPPY_SHOPPING: "DATA_HAPPY_SHOPPING",
  LOADING_CHECKOUT: "LOADING_CHECKOUT",
};

export const WALLET = {
  LOADING_WITHDRAW: "LOADING_WITHDRAW",
  LOADING_DEPOSIT: "LOADING_DEPOSIT",
};

export const INVOICE = {
  LOADING: "LOADING_INVOICE",
  DATA: "DATA_INVOICE",
};

export const CART = {
  LOADING_ADD: "LOADING_ADD_CART",
  DATA: "DATA_CART",
  LOADING_DATA: "LOADING_DATA_CART",
  LOADING_DELETE: "LOADING_DELETE_CART",
};

export const REPORT = {
  DATA_TRANSACTION: "REPORT_DATA_TRANSACTION",
  DATA_PURCHASE: "REPORT_DATA_PURCHASE",
  LOADING_TRANSACTION: "REPORT_LOADING_TRANSACTION",
  LOADING_PURCHASE: "REPORT_LOADING_PURCHASE",
};

export const PIN = {
  LOADING_AKTIVASI: "LOADING_AKTIVASI_PIN",
  LOADING_AKTIVASI_HAPPY_SHOPPING: "LOADING_HAPPY_SHOPPING_PIN",
  LOADING_AKTIVASI_SMART_CONTRACT: "LOADING_SMART_CONTRACT_PIN",
};
