export const STRING_COOKIES = {
  token: "__kolabiz__token",
  user: "__kolabiz__user",
  info: "__kolabiz__info",
};

export const LOGIN = {
  SUCCESS: "LOGIN_SUCCESS",
  LOADING: "LOGIN_LOADING",
};

export const AUTH_USER = {
  DATA_USER_LOGIN: "DATA_USER_LOGIN",
  DATA_INFO: "DATA_INFO",
  DATA_USER_DETAIL: "DATA_USER_DETAIL",
  DATA_PIN: "DATA_PIN",
  LOADING: "LOADING_LOGIN",
  LOADING_PIN: "LOADING_PIN",
  VALIDATE_USERNAME: "VALIDATE_USERNAME",
  LOADING_VALIDATE_USERNAME: "LOADING_VALIDATE_USERNAME",
};

export const ADDRESS = {
  DATA_PROVINCE: "DATA_PROVINCE",
  LOADING_PROVINCE: "LOADING_PROVINCE",
  DATA_CITY: "DATA_CITY",
  LOADING_CITY: "LOADING_CITY",
  DATA_DISTRICTS: "DATA_DISTRICTS",
  LOADING_DISTRICTS: "LOADING_DISTRICTS",
};
