export const LOGIN = {
  SUCCESS: "LOGIN_SUCCESS",
  LOADING: "LOGIN_LOADING",
};

export const AUTH_USER = {
  DATA_USER_LOGIN: "DATA_USER_LOGIN",
  DATA_INFO: "DATA_INFO",
  DATA_USER_DETAIL: "DATA_USER_DETAIL",
  DATA_PIN: "DATA_PIN",
  LOADING: "LOADING_LOGIN",
  LOADING_PIN: "LOADING_PIN",
};
